image: Visual Studio 2017
platform:
- x64

clone_folder: c:\gopath\src\github.com\skycoin\cx

environment:
  GOPATH: c:\gopath

stack: go 1.11

# Install dev dependencies
install:
  - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl
  - set PATH=c:\cygwin64\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go get github.com/skycoin/skycoin/...
  - go get github.com/go-gl/gl/v2.1/gl
  - go get github.com/go-gl/glfw/v3.2/glfw
  - go get github.com/go-gl/gltext
  - go get github.com/blynn/nex
  - go get github.com/cznic/goyacc
  - go get github.com/skycoin/cx/...

before_build:
  - nex -e %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.nex
  - goyacc -o %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.go %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.y
  - nex -e %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.nex
  - goyacc -o %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.go %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.y

build_script:
  - go build -race -tags full -i -o %GOPATH%\bin\cx github.com\skycoin\cx\cxgo\

test_script:
  - go test -race -tags full -i -o %GOPATH%\bin\cx github.com\skycoin\cx\cxgo\
