version: 1.0.{build}
image: Visual Studio 2017
platform:
- x64

clone_folder: c:\gopath\src\github.com\skycoin\cx

environment:
  GOPATH: c:\gopath
  MINGW_W64: c:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64

stack: go 1.11

# cache to build faster
cache:
  - '%GOPATH%\src\github.com\skycoin\skycoin'
  - '%GOPATH%\src\github.com\go-gl\gl'
  - '%GOPATH%\src\github.com\go-gl\glfw'
  - '%GOPATH%\src\github.com\go-gl\gltext'
  - '%GOPATH%\src\github.com\blynn\nex'
  - '%GOPATH%\src\github.com\cznic\goyacc'

# Install dev dependencies
install:
  - set PATH=%MINGW_W64\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go get github.com/skycoin/skycoin/...
  - go get github.com/go-gl/gl/v2.1/gl
  - go get github.com/go-gl/glfw/v3.2/glfw
  - go get github.com/go-gl/gltext
  - go get github.com/blynn/nex
  - go get github.com/cznic/goyacc
  - go get github.com/skycoin/cx/...

before_build:
  - nex -e %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.nex
  - goyacc -o %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.go %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo0\cxgo0.y
  - nex -e %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.nex
  - goyacc -o %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.go %GOPATH%\src\github.com\skycoin\cx\cxgo\cxgo.y

build_script:
  - go build -race -tags full -i -o %GOPATH%\bin\cx github.com\skycoin\cx\cxgo\

# Copy cx executable into project folder to avoid relative path problems
after_build:
  - copy c:\gopath\bin\cx c:\gopath\src\github.com\skycoin\cx

test_script:
  - go test -race -tags full -i -o %GOPATH%\bin\cx github.com\skycoin\cx\cxgo\

artifacts:
  - path: 'cx'
    name: cx-win64
