# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
language: go
sudo: required

# Version of go to use
go:
  - "1.11.x"

# Placed source code under GOPATH
go_import_path: github.com/skycoin/cx

# Define global variables
env:
  - GOARCH=amd64

# Use a matrix to define SO and possible future changes
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

# Install dev dependencies
before_install:
  - ./.ci-scripts/install-deps.sh

# Install necessaries go packages
install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then sudo apt install libxi-dev libgl1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev ; fi
  - cx.sh

# Generate cxgo necessaries files
before_script:
  - $GOPATH/bin/nex -e $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.nex
  - $GOPATH/bin/goyacc -o $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.y
  - $GOPATH/bin/nex -e $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.nex
  - $GOPATH/bin/goyacc -o $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.go $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.y

# Build, test & run cx test
script:
  - go build -race -tags full -i -o $GOPATH/bin/cx github.com/skycoin/cx/cxgo/
  - go test -race -tags full -i -o $GOPATH/bin/cx github.com/skycoin/cx/cxgo/
  - $GOPATH/bin/cx $GOPATH/src/github.com/skycoin/cx/tests/main.cx ++wdir=$GOPATH/src/github.com/skycoin/cx/tests

# Notifications to Telegram channel
notifications:
  email: false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
