# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
language: go
sudo: required

# Version of go to use
go:
  - "1.11.x"

# Placed source code under GOPATH
go_import_path: github.com/skycoin/cx

# Define global variables
env:
  - GOARCH=amd64

# Use a matrix to define SO and possible future changes
matrix:
  include:
    - os: linux
      dist: xenial

    # - os: osx

# Install dev dependencies
before_install:
  - ./.ci-scripts/install-deps.sh
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get upgrade -y && sudo apt-get install --no-install-recommends -y libglib2.0-dev gtk+3.0 libgtk-3-dev libpango1.0-dev libcairo2-dev libperl-dev libgtk2.0-dev gir1.2-gtk-3.0 libxi-dev libgl1-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -o MacPorts-HighSierra.pkg https://github.com/macports/macports-base/releases/download/v2.5.4/MacPorts-2.5.4-10.13-HighSierra.pkg && sudo installer -pkg MacPorts-HighSierra.pkg -target / && brew install gtk && sudo port install gtk3; fi

# Install necessaries go packages
install:
  - go get -v github.com/skycoin/skycoin/...
  - go get -v github.com/go-gl/gl/v2.1/gl
  - go get -v github.com/go-gl/glfw/v3.2/glfw
  - go get -v github.com/go-gl/gltext
  - go get -v github.com/blynn/nex
  - go get -v github.com/cznic/goyacc
  - go get -v ./...

# Generate cxgo necessaries files
before_script:
  - $GOPATH/bin/nex -e $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.nex
  - $GOPATH/bin/goyacc -o $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.y
  - $GOPATH/bin/nex -e $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.nex
  - $GOPATH/bin/goyacc -o $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.go $GOPATH/src/github.com/skycoin/cx/cxgo/cxgo.y

# Build & test
script:
  - go build -race -tags full -i -o $GOPATH/bin/cx github.com/skycoin/cx/cxgo/
  - go test -race -tags full -i -o $GOPATH/bin/cx github.com/skycoin/cx/cxgo/
  - $GOPATH/bin/cx $GOPATH/src/github.com/skycoin/cx/tests

# Notifications to Telegram channel
notifications:
  email: false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
